export const questions = [
  {
    id: 0,
    isActive: false,
    question: "Hangisi bir programlama dilidir?",
    options: [
      { id: 1, option: "HTML" },
      { id: 2, option: "Python" },
      { id: 3, option: "CSS" },
      { id: 4, option: "Photoshop" },
    ],
    correntAnswerId: 2,
    isAnswerCorrect: undefined,
  },
  {
    id: 1,
    isActive: false,
    question: "HTML'in açılımı nedir?",
    options: [
      { id: 1, option: "HyperTransfer Marking Language" },
      { id: 2, option: "HyperText Markup Language" },
      { id: 3, option: "HighText Machine Learning" },
      { id: 4, option: "HyperTool Marking Logic" },
    ],
    correntAnswerId: 2,
    isAnswerCorrect: undefined,
  },
  {
    id: 2,
    isActive: false,
    question: "Hangisi bir NoSQL veritabanıdır?",
    options: [
      { id: 1, option: "Oracle" },
      { id: 2, option: "MongoDB" },
      { id: 3, option: "MySQL" },
      { id: 4, option: "PostgreSQL" },
    ],
    correntAnswerId: 2,
    isAnswerCorrect: undefined,
  },
  {
    id: 3,
    isActive: false,
    question: "JavaScript hangi amaçla kullanılır?",
    options: [
      { id: 1, option: "Web sayfalarını dinamik hale getirmek" },
      { id: 2, option: "Sunucu kurmak" },
      { id: 3, option: "Veritabanı yönetmek" },
      { id: 4, option: "Metin düzenlemek" },
    ],
    correntAnswerId: 1,
    isAnswerCorrect: undefined,
  },
  {
    id: 4,
    isActive: false,
    question: "Hangisi bir CSS özelliğidir?",
    options: [
      { id: 1, option: "fetch" },
      { id: 2, option: "alert" },
      { id: 3, option: "print" },
      { id: 4, option: "color" },
    ],
    correntAnswerId: 4,
    isAnswerCorrect: undefined,
  },
  {
    id: 5,
    isActive: false,
    question: "Hangisi bir yazılım geliştirme metodolojisidir?",
    options: [
      { id: 1, option: "React" },
      { id: 2, option: "Docker" },
      { id: 3, option: "Agile" },
      { id: 4, option: "JIRA" },
    ],
    correntAnswerId: 3,
    isAnswerCorrect: undefined,
  },
  {
    id: 6,
    isActive: false,
    question:
      "Python'da listelerde eleman eklemek için hangi metod kullanılır?",
    options: [
      { id: 1, option: "add()" },
      { id: 2, option: "append()" },
      { id: 3, option: "insert()" },
      { id: 4, option: "push()" },
    ],
    correntAnswerId: 2,
    isAnswerCorrect: undefined,
  },
  {
    id: 7,
    isActive: false,
    question: "REST API'lerde kullanılan HTTP metodu hangisidir?",
    options: [
      { id: 1, option: "RUN" },
      { id: 2, option: "EXECUTE" },
      { id: 3, option: "GET" },
      { id: 4, option: "LOAD" },
    ],
    correntAnswerId: 3,
    isAnswerCorrect: undefined,
  },
  {
    id: 8,
    isActive: false,
    question: "Hangisi bir sürüm kontrol sistemi aracıdır?",
    options: [
      { id: 1, option: "Git" },
      { id: 2, option: "Excel" },
      { id: 3, option: "Apache" },
      { id: 4, option: "Java" },
    ],
    correntAnswerId: 1,
    isAnswerCorrect: undefined,
  },
  {
    id: 9,
    isActive: false,
    question:
      "Java'da hangi anahtar kelime bir sınıf oluşturmak için kullanılır?",
    options: [
      { id: 1, option: "define" },
      { id: 2, option: "object" },
      { id: 3, option: "class" },
      { id: 4, option: "create" },
    ],
    correntAnswerId: 3,
    isAnswerCorrect: undefined,
  },
];
